### ISSUE TITLE
watch panel dump

### ISSUE THREAD

**Issue by sbobber** [caronc/ultrasync#7]
:beetle: **Describe the bug**

watch panel dump

:bulb: **Screenshots and Logs**

```
[fed]$ ./bin/ultrasync -w -c ~/.config/ultrasync/vpnnat.cfg
2021-01-15 14:54:46 [001] F1                      : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] F2                      : Ready
2021-01-15 14:54:46 [001] F3                      : Ready
2021-01-15 14:54:46 [001] P1                      : Ready
2021-01-15 14:54:46 [001] P2                      : Ready
2021-01-15 14:54:46 [001] F4                      : Ready
2021-01-15 14:54:46 [001] F5                      : Ready
2021-01-15 14:54:46 [001] F6                      : Ready
2021-01-15 14:54:46 [001] P3                      : Ready
2021-01-15 14:54:46 [001] P4                      : Ready
2021-01-15 14:54:46 [001] IR1                     : Ready
2021-01-15 14:54:46 [001] IR2                     : Ready
2021-01-15 14:54:46 [001] IR3                     : Ready
2021-01-15 14:54:46 [001] IR4                     : Ready
2021-01-15 14:54:46 [001] IR5                     : Ready
2021-01-15 14:54:46 [001] IR6                     : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] TMP                     : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [001] -                       : Ready
2021-01-15 14:54:46 [081] F                #1     : Armed Away
2021-01-15 14:54:46 [000] B                #2     : Armed Away
---
Traceback (most recent call last):
  File "./bin/ultrasync", line 71, in <module>
    main()
  File "/home/xxx/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xxx/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/04_configurazioni/ultrasync_caronc/ultrasync-xgen-nx64ip-support/ultrasync/cli.py", line 199, in main
    results = usync.details()
  File "/home/xxx/04_configurazioni/ultrasync_caronc/ultrasync-xgen-nx64ip-support/ultrasync/main.py", line 588, in details
    if not self.update(max_age_sec=max_age_sec):
  File "/home/xxx/04_configurazioni/ultrasync_caronc/ultrasync-xgen-nx64ip-support/ultrasync/main.py", line 573, in update
    if not self._sequence():
  File "/home/xxx/04_configurazioni/ultrasync_caronc/ultrasync-xgen-nx64ip-support/ultrasync/main.py", line 1829, in _sequence
    return getattr(self, '_{}_sequence'.format(self.vendor))()
  File "/home/xxx/04_configurazioni/ultrasync_caronc/ultrasync-xgen-nx64ip-support/ultrasync/main.py", line 2046, in _comnav_sequence
    if area['sequence'] != a_seq[bank]:
IndexError: list index out of range
```

:computer: **Your System Details:**
 - OS: Fedora 32
 - kernel: 5.9.16-100.fc32.x86_64
 - Python Version: 3.8.6

:crystal_ball: **Additional context**
- same error on raspberry with pi os

**Comment by caronc** [comment]
@sbobber,

I can definitely have a look into this for you! :slightly_smiling_face: .  I also noticed you're using the `ultrasync-xgen-nx64ip-support` branch.  Is that intentional?

What i'll need from you is a `ultrasync --debug-dump` call from you.  It will produce a `.zip` file with everything i need about your security panel (don't worry, there is no pin and/or password information in this dump).  It will however share with me your zones/areas.  I need this so i can re-produce your situation though and attempt to resolve it.

Would you be able to do that for me and pass the `zip` file back through this ticket?  If you have any privacy concerns just email it to me directly (@ lead2gold@gmail.com).

Chris

**Comment by sbobber** [comment]
Hi,
the problem is the same in all version, I've opened the issue with the latest release, do you preferer the dump with the stable one?

**Comment by caronc** [comment]
Whatever version you have will work great; they all produce the same file.  I was only asking about the branch thinking that maybe you also had an xGen panel too.  If your panel is Interlogix or ComNav then it really doesn't matter where the dump comes from :slightly_smiling_face:

**Comment by caronc** [comment]
@sbobber,

Just letting you know i got the dump file; thank you!  I'll hopefully have a look at it this weekend.  :+1:

**Comment by caronc** [comment]
I think i might have fixed this.  I got your issue mixed up with another which is why the branch naming is off.  But if you want to check out the `8-comnav-all-zone-fix` branch and give it a try.  It might fix things for you.

There was a MAJOR flaw in ALL my releases of `ultrasync` that you uncovered in how i was interpreting bank information.  I thought the bank information mapped `1:1` to the Area in question and they do not; not at all.  I rewrote how `sequence` information is tracked completely.  I'm hoping this will rectify the issue you're having (i may have introduced more as this is a pretty significant change).

Please test it out and let me know.

**Comment by sbobber** [comment]
the dump is resolved, but something strange appear, seem that the -w flag check only the first area, but let me do more test

**Comment by caronc** [comment]
By chance are the entries you have defined as a dash `-` valid? I thought these were invalid and added them to the ignore list. Should I undo this?

**Comment by caronc** [comment]
Hi, i haven't heard back from you.  I've gone ahead and merged the branch since it resolved your issue.
I left the `-` zone entries as _to be ignored_.  If this isn't correct, just let me know.

**Comment by sbobber** [comment]
I tried 0.9.3, now work like charm, thanks

**Comment by caronc** [comment]
Closing issue since it's been resolved and it got a little forgotten (just doing house cleaning).
